name: Deploy Terraform Configuration

on: 
  push:
  workflow_dispatch: # 手動トリガーを追加

jobs:
  deploy-terraform:
    name: Apply Terraform Configuration to AWS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-1
      ECR_REPO: wordpress
      IMAGE_TAG: ${{ github.sha }}
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.4.0  # 必要なTerraformのバージョンを指定

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build Docker image
      run: |
        docker build -t $ECE_REPO:$IMAGE_TAG .

    - name: Tag & Push to ECR
      run: |
        ECR_URI=$(aws ecr describe-repositories --repository-names $ECR_REPO --query 'repositories[0].repositoryUri' --output text)
        docker tag $ECR_REPO:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
        docker push $ECR_URI:$IMAGE_TAG

    - name: Initialize Terraform
      run: cd terraform && terraform init

    - name: Terraform Plan
      run: cd terraform && terraform plan

    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve